/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import entity.Student;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import manager.StudentManager;
import manager.classManager;
import manager.schoolstageManager;

/**
 *
 * @author User
 */
public class Score extends javax.swing.JFrame {

    private schoolstageManager mySchoolStageManager;
    private classManager myClassManager;
    private StudentManager myStudentManager;
    public Score(StudentManager myStudentManager, schoolstageManager mySchoolStageManager,classManager myClassManager) {
        initComponents();
        this.mySchoolStageManager = mySchoolStageManager;
        this.myClassManager = myClassManager;
        this.myStudentManager = myStudentManager;
        String a = (String) this.jComboBox1.getSelectedItem();
        ArrayList<String> res = new ArrayList<>();
        for (entity.Class i : myClassManager.getListClass()) {
            if (i.getClassSchoolstageID().equals(a)) {
                res.add(i.getClassName());
            }
        }

        DefaultComboBoxModel model = new DefaultComboBoxModel(res.toArray());
        this.jComboBox2.setModel(model);
        DefaultTableModel model1 = (DefaultTableModel) jTable1.getModel();
        int count=1;
        for (int i = 0; i < myStudentManager.getListStudent().size(); i++) {
            Student res1 = (Student)myStudentManager.getListStudent().get(i);
            if (res1.getSchoolStage().equals((String) this.jComboBox1.getSelectedItem())) {
                if (res1.getStuClass().equals((String) this.jComboBox2.getSelectedItem())) {
                    model1.addRow(new Object[]{count++, res1.getHolyName(), res1.getFirstName(), res1.getLastName(), res1.getSchoolStage(), res1.getStuClass(), res1.getMieng(),res1.getMuoilam(),res1.getMottiet(),res1.getThi()});
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jTextField1a = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jTextField2a = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTextField3a = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jTextField2a1 = new javax.swing.JTextField();
        jTextField3a1 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jTextField1a1 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jTextField2a2 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jTextField3a2 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jTextField2a3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên Thánh", "Họ và Tên Đệm", "Tên", "Ngành", "Lớp", "Miệng", "15'", "45'", "Thi HK"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Chọn Ngành :");

        jLabel2.setText("Chọn Lớp :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new manager.schoolstageManager().getListSchoolstageName())
        );
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Bảng Điểm");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Thông Tin Học Sinh");

        jLabel34.setText("Tên Thánh :");

        jTextField1a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1aActionPerformed(evt);
            }
        });

        jLabel35.setText("Họ và tên đệm : ");

        jTextField2a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2aActionPerformed(evt);
            }
        });

        jLabel36.setText("Tên :");

        jLabel43.setText("Ngành Học");

        jLabel44.setText("Lớp :");

        jTextField2a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2a1ActionPerformed(evt);
            }
        });

        jTextField3a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3a1ActionPerformed(evt);
            }
        });

        jLabel37.setText("Điểm Miệng :");

        jTextField1a1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextField1a1InputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jTextField1a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1a1ActionPerformed(evt);
            }
        });
        jTextField1a1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1a1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1a1KeyTyped(evt);
            }
        });

        jLabel38.setText("Điểm 15 Phút : ");

        jTextField2a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2a2ActionPerformed(evt);
            }
        });
        jTextField2a2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2a2KeyTyped(evt);
            }
        });

        jLabel39.setText("Điểm 45 Phút :");

        jTextField3a2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3a2KeyTyped(evt);
            }
        });

        jLabel45.setText("Điểm thi Học Kì :");

        jTextField2a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2a3ActionPerformed(evt);
            }
        });
        jTextField2a3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2a3KeyTyped(evt);
            }
        });

        jButton1.setText("Lưu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Xóa điểm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Thoát");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(323, 323, 323)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel44))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1a)
                                    .addComponent(jTextField2a)
                                    .addComponent(jTextField3a)
                                    .addComponent(jTextField2a1)
                                    .addComponent(jTextField3a1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(132, 132, 132)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                    .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1a1)
                                    .addComponent(jTextField2a2)
                                    .addComponent(jTextField3a2)
                                    .addComponent(jTextField2a3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(jLabel4)))
                        .addGap(0, 296, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(525, 525, 525))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox2))
                    .addComponent(jComboBox1))
                .addGap(9, 9, 9)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField2a1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField3a1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField1a1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2a2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3a2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2a3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(24, 24, 24))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 51));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icon/icons8_Marker_Pen_48px.png"))); // NOI18N
        jLabel5.setText(" Quản Lý Điểm");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 480, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1aActionPerformed

    private void jTextField2aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2aActionPerformed

    private void jTextField2a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2a1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2a1ActionPerformed

    private void jTextField3a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3a1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3a1ActionPerformed

    private void jTextField1a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1a1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1a1ActionPerformed

    private void jTextField2a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2a2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2a2ActionPerformed

    private void jTextField2a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2a3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2a3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    String a = (String) this.jComboBox1.getSelectedItem();
    
        DefaultComboBoxModel model = (DefaultComboBoxModel) this.jComboBox2.getModel();
        model.removeAllElements();
        for (String i : this.myClassManager.getListClassByShoolStage(a)){
            model.addElement(i);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!this.jTable1.isRowSelected(this.jTable1.getSelectedRow())) return;
        if ((this.jTextField1a1.getText().equals("") || (Integer.parseInt(this.jTextField1a1.getText())<0 || Integer.parseInt(this.jTextField1a1.getText())>10))||(this.jTextField2a2.getText().equals("") || (Integer.parseInt(this.jTextField2a2.getText())<0 || Integer.parseInt(this.jTextField2a2.getText())>10))||(this.jTextField3a2.getText().equals("") || (Integer.parseInt(this.jTextField3a2.getText())<0 || Integer.parseInt(this.jTextField3a2.getText())>10))||(this.jTextField2a3.getText().equals("") || (Integer.parseInt(this.jTextField2a3.getText())<0 || Integer.parseInt(this.jTextField2a3.getText())>10))){
            JOptionPane.showMessageDialog(this, "Kiểm tra lại điểm", "Cảnh báo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int n = this.jTable1.getSelectedRow();
        int temp = this.myStudentManager.findChangeStudent((String) this.jTable1.getValueAt(n, 1),(String) this.jTable1.getValueAt(n, 2),(String) this.jTable1.getValueAt(n, 3),(String) this.jTable1.getValueAt(n, 4),(String) this.jTable1.getValueAt(n, 5));
        
        
        
        
        this.myStudentManager.changeScore(temp, Integer.parseInt(this.jTextField1a1.getText()), Integer.parseInt(this.jTextField2a2.getText()), Integer.parseInt(this.jTextField3a2.getText()), Integer.parseInt(this.jTextField2a3.getText()));
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        int count=1;
        for (int i = 0; i < myStudentManager.getListStudent().size(); i++) {
            Student res = (Student)myStudentManager.getListStudent().get(i);
            if (res.getSchoolStage().equals((String) this.jComboBox1.getSelectedItem())) {
                if (res.getStuClass().equals((String) this.jComboBox2.getSelectedItem())) {
                    model.addRow(new Object[]{count++, res.getHolyName(), res.getFirstName(), res.getLastName(), res.getSchoolStage(), res.getStuClass(), res.getMieng(),res.getMuoilam(),res.getMottiet(),res.getThi()});
                }
            }
        }
        this.jTextField1a.setText("");
        this.jTextField2a.setText("");
        this.jTextField3a.setText("");
        this.jTextField2a1.setText("");
        this.jTextField3a1.setText("");
        this.jTextField1a1.setText("");
        this.jTextField2a2.setText("");
        this.jTextField3a2.setText("");
        this.jTextField2a3.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        int count=1;
        ArrayList<Student> temp = this.myStudentManager.getListStudent();
        for (int i = 0; i < temp.size(); i++) {
            Student res = temp.get(i);
            if (res.getSchoolStage().equals((String) this.jComboBox1.getSelectedItem())) {
                if (res.getStuClass().equals((String) this.jComboBox2.getSelectedItem())) {
                    model.addRow(new Object[]{count++, res.getHolyName(), res.getFirstName(), res.getLastName(), res.getSchoolStage(), res.getStuClass(), res.getMieng(),res.getMuoilam(),res.getMottiet(),res.getThi()});
                }
            }
        }
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int n = this.jTable1.getSelectedRow();
        this.jTextField1a.setText((String) this.jTable1.getValueAt(n,1));
        this.jTextField2a.setText((String) this.jTable1.getValueAt(n,2));
        this.jTextField3a.setText((String) this.jTable1.getValueAt(n,3));
        this.jTextField2a1.setText((String) this.jTable1.getValueAt(n,4));
        this.jTextField3a1.setText((String) this.jTable1.getValueAt(n,5));
        this.jTextField1a1.setText( ((String)this.jTable1.getValueAt(n,6).toString()));
        this.jTextField2a2.setText(((String)this.jTable1.getValueAt(n,7).toString()));
        this.jTextField3a2.setText(((String)this.jTable1.getValueAt(n,8).toString()));
        this.jTextField2a3.setText(((String)this.jTable1.getValueAt(n,9).toString()));
        this.jTextField1a.setEditable(false);
        this.jTextField2a.setEditable(false);
        this.jTextField3a.setEditable(false);
        this.jTextField2a1.setEditable(false);
        this.jTextField3a1.setEditable(false);
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
//        myStudentManager.myDAO.saveListCDasByte(myStudentManager.getListStudent());
        this.dispose();
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        this.jTextField1a1.setText("0");
        this.jTextField2a2.setText("0");
        this.jTextField3a2.setText("0");
        this.jTextField2a3.setText("0");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1a1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextField1a1InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1a1InputMethodTextChanged

    private void jTextField1a1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1a1KeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField1a1KeyTyped

    private void jTextField1a1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1a1KeyReleased
       
    }//GEN-LAST:event_jTextField1a1KeyReleased

    private void jTextField2a2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2a2KeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField2a2KeyTyped

    private void jTextField3a2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3a2KeyTyped
        if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField3a2KeyTyped

    private void jTextField2a3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2a3KeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField2a3KeyTyped

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1a;
    private javax.swing.JTextField jTextField1a1;
    private javax.swing.JTextField jTextField2a;
    private javax.swing.JTextField jTextField2a1;
    private javax.swing.JTextField jTextField2a2;
    private javax.swing.JTextField jTextField2a3;
    private javax.swing.JTextField jTextField3a;
    private javax.swing.JTextField jTextField3a1;
    private javax.swing.JTextField jTextField3a2;
    // End of variables declaration//GEN-END:variables
}
